const affirmations = [
    "My love for you grows stronger with every season we share.",
    "You are my favorite person, my safest place, and my greatest joy.",
    "Being your husband is one of the greatest privileges of my life.",
    "I still choose you, and I will keep choosing you every day.",
    "You make ordinary moments feel beautiful.",
    "I love the life we are building together.",
    "Your smile can make even the hardest day feel lighter.",
    "I am grateful for your heart, your patience, and your love.",
    "You are beautiful in every season of life.",
    "Home is wherever I am with you.",
    "Thank you for being my partner, my comfort, and my best friend.",
    "I love you for who you are, not for what you do for everyone else.",
    "You are the person I want beside me for every chapter ahead.",
    "Our story is my favorite story.",
    "You bring warmth and kindness wherever you go.",
    "I hope you know how deeply you are loved.",
    "You make my world softer, brighter, and more meaningful.",
    "I am proud to call you my wife.",
    "Every day with you is a gift I never take for granted.",
    "You are more precious to me than words can explain.",
    "You do not have to carry everything alone; I am here with you.",
    "You can rest today. You are loved even when you are doing nothing.",
    "I believe in you, especially on the days you doubt yourself.",
    "You are stronger than this difficult moment.",
    "Whatever today brings, we will face it together.",
    "You are allowed to ask for help, and I will always listen.",
    "Your feelings matter to me.",
    "You do not need to be perfect to be deeply loved.",
    "I see how hard you work, and I am so proud of you.",
    "You are doing better than you think you are.",
    "Take things one breath and one step at a time; I am beside you.",
    "You deserve kindness, peace, and time for yourself.",
    "I will remind you of your strength whenever you forget it.",
    "You have overcome so much, and I know you can overcome this too.",
    "Your dreams matter, and I want to help you pursue them.",
    "You are never a burden to me.",
    "I am here for the celebrations, the quiet days, and everything between.",
    "You can be honest with me about anything.",
    "You are worthy of all the good things coming your way.",
    "I admire your courage, even when you do not feel brave.",
    "You make me want to be a better person.",
    "I will always make room for your hopes, worries, and dreams.",
    "You deserve to feel supported, cherished, and understood.",
    "No matter what changes, you will never face life alone.",
    "I love listening to your thoughts and seeing the world through your eyes.",
    "You are enough exactly as you are.",
    "I am thankful for every laugh, lesson, and memory we share.",
    "You are my calm in the middle of a busy world.",
    "I will keep showing up for you, one day at a time.",
    "Loving you is easy; appreciating you is endless.",
    "You are my forever, and I am grateful for every day with you.",
    "You are the love I hoped for and the life I am grateful to live.",
    "I love the way you make our house feel like home.",
    "You are still the first person I want to tell everything to.",
    "I would find you and choose you in every lifetime.",
    "Your kindness is one of the things I admire most about you.",
    "I love growing older and wiser alongside you.",
    "You make partnership feel like a beautiful adventure.",
    "I am lucky to know your heart as closely as I do.",
    "You are the best part of so many of my days.",
    "I love your laugh, your thoughts, and all the little things that make you you.",
    "Thank you for trusting me with your heart and your life.",
    "You are my favorite hello and my hardest goodbye.",
    "I love discovering new reasons to appreciate you.",
    "You make love feel steady, safe, and exciting all at once.",
    "I am grateful for the quiet moments we share as much as the big ones.",
    "You are the person I want to celebrate and comfort for the rest of my life.",
    "Your presence is a gift I notice every day.",
    "I love you in the easy moments and the difficult ones.",
    "You make my heart feel at home.",
    "You never have to earn my love; it is already yours.",
    "I am on your side, always.",
    "You are allowed to have a hard day without having all the answers.",
    "I trust your judgment, your heart, and your ability to find your way.",
    "You do not have to face this alone when you have me.",
    "I am proud of the way you keep going, even when things are hard.",
    "Your best does not have to look the same every day.",
    "You deserve rest without guilt and care without conditions.",
    "I will listen without trying to rush you through what you feel.",
    "You are allowed to change direction and begin again.",
    "I see the effort behind everything you do, and it matters.",
    "You are capable of more than this moment is asking of you.",
    "I will celebrate every small victory with you.",
    "You can lean on me whenever your own strength feels far away.",
    "You are worthy of being cared for as deeply as you care for others.",
    "I believe your future holds more good than you can see today.",
    "You are not defined by one mistake, one day, or one difficult season.",
    "I will stand beside you while you become everything you are meant to be.",
    "You deserve to take up space and speak your truth.",
    "I am grateful for your honesty, even when the truth is difficult.",
    "You have made my life better simply by being in it.",
    "I will keep learning how to love you better.",
    "You are my teammate in every sense of the word.",
    "Your happiness matters to me, and so does your peace.",
    "I love the woman you are and the woman you are becoming.",
    "You make me proud in ways I do not always say out loud.",
    "There is no version of you that I would abandon.",
    "You can always come home to my arms and my heart.",
    "I am thankful that life gave me you to love.",
    "Our future is something I look forward to with my whole heart.",
    "You are loved in the morning, at midnight, and in every moment between.",
    "No matter where life takes us, I will be grateful that I get to walk beside you."
];

const randomIndex = Math.floor(Math.random() * affirmations.length);
const affirmation = affirmations[randomIndex];

document.getElementById("message").textContent = affirmation;
