const affirmations = [
    "You are capable of more than you realise.",
    "You deserve good things.",
    "You are making progress, even when you cannot see it.",
    "You are enough exactly as you are.",
    "You have overcome difficult things before.",
    "You can handle whatever today brings.",
    "You are allowed to take things one step at a time.",
    "You bring something unique to the world.",
    "You are worthy of kindness, including from yourself.",
    "You are stronger than you think.",
    "Your effort matters.",
    "You are growing every day.",
    "You deserve to feel proud of yourself.",
    "You are allowed to make mistakes and learn from them.",
    "You have the courage to begin again.",
    "You are doing better than you think.",
    "You have a valuable perspective to offer.",
    "You are worthy of respect and appreciation.",
    "You can choose what deserves your energy today.",
    "You are becoming the person you want to be.",
    "You are resilient.",
    "Your presence makes a difference.",
    "You don't have to have everything figured out.",
    "You are allowed to rest without earning it first.",
    "You can trust yourself to find your way.",
    "You have permission to put yourself first sometimes.",
    "You are worthy of happiness.",
    "You can create something wonderful from where you are.",
    "Your best is enough.",
    "You are learning and evolving.",
    "You have more options than you can currently see.",
    "You are deserving of love and connection.",
    "You can do hard things.",
    "You are allowed to change your mind.",
    "You are not defined by your worst day.",
    "You have made it through every difficult day so far.",
    "You are worthy even when you are not productive.",
    "Your dreams are worth pursuing.",
    "You have a reason to be hopeful.",
    "You are allowed to celebrate small victories.",
    "You have qualities that other people appreciate.",
    "You are capable of creating positive change.",
    "You are more than your mistakes.",
    "You can start again at any moment.",
    "You deserve to speak to yourself with compassion.",
    "You have something meaningful to contribute.",
    "You are becoming stronger through what you experience.",
    "You can take up space.",
    "You are allowed to be yourself.",
    "You deserve moments of peace.",
    "You are capable of surprising yourself.",
    "You have already come a long way.",
    "You can focus on what you can control.",
    "You are worthy of being heard.",
    "You don't need anyone's permission to believe in yourself.",
    "You can make today a little better.",
    "You are allowed to have ambitious dreams.",
    "You are valuable simply because you are you.",
    "You can learn something from every experience.",
    "You deserve patience while you grow.",
    "You are capable of adapting to change.",
    "Your feelings are valid.",
    "You can choose courage over perfection.",
    "You are not behind; your journey is your own.",
    "You have the ability to make a difference.",
    "You deserve to enjoy the good moments.",
    "You are allowed to say no.",
    "You can give yourself another chance.",
    "You are worthy of meaningful relationships.",
    "You have strengths you may not recognise yet.",
    "You are capable of making good decisions.",
    "You can take things one day at a time.",
    "You deserve to feel comfortable being yourself.",
    "You are allowed to outgrow old versions of yourself.",
    "You have the power to choose your next step.",
    "You are worthy of encouragement.",
    "You can turn setbacks into lessons.",
    "You are doing enough.",
    "You deserve to believe that things can get better.",
    "You have a unique contribution to make.",
    "You are capable of finding joy in ordinary moments.",
    "You can be both a work in progress and proud of yourself.",
    "You deserve forgiveness, including your own.",
    "You are allowed to take up your own time and space.",
    "You can trust yourself to keep moving forward.",
    "You are stronger for having kept going.",
    "You deserve kindness on difficult days.",
    "You can accomplish things that once seemed impossible.",
    "You are worthy of celebrating.",
    "You don't have to compare your journey with anyone else's.",
    "You are capable of creating a life that feels right for you.",
    "You deserve to feel hopeful about your future.",
    "You can let go of what no longer serves you.",
    "You are allowed to be proud of how far you've come.",
    "You have everything you need to take the next step.",
    "You are worthy of good opportunities.",
    "You can make a difference with small acts of kindness.",
    "You are becoming more confident with every experience.",
    "You deserve to give yourself credit.",
    "You are capable, valuable, and worthy.",
    "Something good may be closer than you think."
];

const randomIndex = Math.floor(Math.random() * affirmations.length);
const affirmation = affirmations[randomIndex];

document.getElementById("message").textContent = affirmation;
